library(processR)
library(foreign)
library(ggplot2)
data=read.csv('C:/data/wd/Wellbeing_and_lifestyle_data_Kaggle.csv')
head(data)
data= data.frame(data$SUPPORTING_OTHERS,data$DONATION,data$PERSONAL_AWARDS,data$WORK_LIFE_BALANCE_SCORE)
head(data)
names(data)<- c('supporting','donation','personal_awards','wlbs')
data$wlbs=data$wlbs/10
head(data)
la<-list(X='supporting',Y='wlbs',M=c('donation','personal_awards'))
drawConcept(labels=la,nodemode=1)
drawModel(labels=la,nodemode=1)
process(data=data,y='wlbs',x='supporting',m=c('donation','personal_awards'),model=3,boot=5000,bc=1,center=2,
        contrast=1,plot=1,seed=72520)
